name: movies_asd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.2
  hive_ce_generator: ^1.8.2
  json_serializable: ^6.9.4
  mockito: ^5.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
