name: movies_asd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.2
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - .env
