import 'package:flutter/material.dart';

import 'colors.dart';

getTheme({required bool isDarkMode}) {
  if (isDarkMode) {
    return ThemeData.dark().copyWith(
      colorScheme: const ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffb9c3ff),
        surfaceTint: Color(0xffb9c3ff),
        onPrimary: Color.fromARGB(255, 201, 94, 32),
        primaryContainer: Color(0xff08546C),
        onPrimaryContainer: Color(0xffA0BACC),
        secondary: Color(0xffc3c5dd),
        onSecondary: Color.fromARGB(255, 66, 52, 44),
        onTertiary: Color(0xff44263e),
        error: Color(0xffffb4ab),
        onError: Color(0xff690005),
        surface: Color.fromARGB(255, 24, 23, 18),
        onSurface: Color(0xffe3e1e9),
        inverseSurface: Color(0xffe3e1e9),
        inversePrimary: Color(0xff505b92),
        primaryFixed: Color(0xffdde1ff),
        onPrimaryFixed: Color(0xff08164b),
        primaryFixedDim: Color(0xffb9c3ff),
        onPrimaryFixedVariant: Color(0xff384379),
        secondaryFixed: Color(0xffdfe1f9),
        onSecondaryFixed: Color(0xff171b2c),
        secondaryFixedDim: Color(0xffc3c5dd),
        onSecondaryFixedVariant: Color(0xff424659),
        tertiaryFixed: Color(0xffffd7f3),
        onTertiaryFixed: Color.fromARGB(255, 128, 26, 112),
        tertiaryFixedDim: Color(0xffe5bad9),
        onTertiaryFixedVariant: Color(0xff5c3c56),
        surfaceDim: Color(0xff121318),
        surfaceBright: Color(0xff38393f),
        surfaceContainerLowest: Color(0xff0d0e13),
        surfaceContainerLow: Color(0xff1b1b21),
        surfaceContainer: Color.fromARGB(255, 225, 81, 18),
        surfaceContainerHigh: Color.fromARGB(255, 214, 39, 39),
        surfaceContainerHighest: Color.fromARGB(255, 179, 106, 70),
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: AppColors.dark,
        elevation: 0,
      ),
      scaffoldBackgroundColor: AppColors.darkLight,
    );
  }
  return ThemeData.light().copyWith(
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff505b92),
      surfaceTint: Color(0xff505b92),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffA0BACC),
      onPrimaryContainer: Color(0xff08164b),
      secondary: Color(0xff5a5d72),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffdfe1f9),
      onSecondaryContainer: Color(0xff171b2c),
      tertiary: Color(0xff76546e),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffffd7f3),
      onTertiaryContainer: Color(0xff2c1228),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      surface: Color(0xfffbf8ff),
      onSurface: Color(0xff1b1b21),
      onSurfaceVariant: Color(0xff45464f),
      outline: Color(0xff767680),
      outlineVariant: Color(0xffc6c5d0),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff303036),
      inversePrimary: Color(0xffb9c3ff),
      primaryFixed: Color(0xffdde1ff),
      onPrimaryFixed: Color(0xff08164b),
      primaryFixedDim: Color(0xffb9c3ff),
      onPrimaryFixedVariant: Color(0xff384379),
      secondaryFixed: Color(0xffdfe1f9),
      onSecondaryFixed: Color(0xff171b2c),
      secondaryFixedDim: Color(0xffc3c5dd),
      onSecondaryFixedVariant: Color(0xff424659),
      tertiaryFixed: Color(0xffffd7f3),
      onTertiaryFixed: Color(0xff2c1228),
      tertiaryFixedDim: Color(0xffe5bad9),
      onTertiaryFixedVariant: Color(0xff5c3c56),
      surfaceDim: Color(0xffdbd9e0),
      surfaceBright: Color(0xfffbf8ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff5f2fa),
      surfaceContainer: Color(0xffefedf4),
      surfaceContainerHigh: Color(0xffe9e7ef),
      surfaceContainerHighest: Color(0xffe3e1e9),
    ),
    appBarTheme: const AppBarTheme(
      backgroundColor: Colors.white,
      elevation: 0,
      iconTheme: IconThemeData(color: AppColors.dark),
    ),
    scaffoldBackgroundColor: Colors.white,
  );
}
